name: Discord Bot Workflow

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi
          pip install gspread

      - run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo '${{ secrets.GCP_CREDENTIALS }}' > CREDENTIALS.json

      - run: python main.py